Repository SoftwareEngineeringII-Team09/se-2022-09-HikeTracker, pull requests merged in 2022-12, with the labels that each got.

#47 Updated linking of start/end points
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeManager.js
  code/server/controllers/ParkingLotManager.js
  code/server/controllers/PointManager.js
  code/server/dbschema.sql
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/hike.router.js
Labels: enhancement

#50 Updated Point, ParkingLot and Hut attributes
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeManager.js
  code/server/controllers/HikeRefPointManager.js
  code/server/controllers/HutManager.js
  code/server/controllers/ParkingLotManager.js
  code/server/dao/model/Hut.js
  code/server/dao/model/ParkingLot.js
  code/server/dao/model/Point.js
  code/server/dbschema.sql
  code/server/dbschemaTest.sql
  code/server/routes/hut.router.js
  code/server/routes/parkingLot.router.js
  code/server/routes/test.router.js
  code/server/setupDB.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/__tests__/HikeRefPoint.test.js
  code/server/test/__tests__/Hut.test.js
  code/server/test/__tests__/ParkingLot.test.js
  code/server/test/__tests__/Point.test.js
  code/server/test/hike.js
  code/server/test/hut.js
  code/server/test/integration-utils.js
  code/server/test/parkingLot.js
  code/server/test/unit-utils.js
Labels: bug, enhancement, tests

#51 Added GET hikes by writerId, updated GET hikes and GET hikes by hikeId
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeManager.js
  code/server/routes/hike.router.js
  code/server/test/__tests__/Hike.test.js
Labels: enhancement, tests

#49 Hike endpoints
  README.md
  code/client/cypress/e2e/hike-form.spec.cy.js
  code/client/cypress/e2e/update-hike-endpoints.spec.cy.js
  code/client/cypress/fixtures/example.json
  code/client/cypress/fixtures/hikes/hike1.json
  code/client/cypress/fixtures/huts/hut1.json
  code/client/cypress/fixtures/parkingLots/parkingLot1.json
  code/client/cypress/fixtures/tracks/gpxTestTrack.gpx
  code/client/cypress/support/commands.js
  code/client/src/App.jsx
  code/client/src/assets/marker.png
  code/client/src/components/features/HikeDetails/HikeEndpoint.jsx
  code/client/src/components/features/HikeDetails/HikeEndpoint.test.jsx
  code/client/src/components/features/HikeDetails/TrackMap.jsx
  code/client/src/components/features/HikeDetails/TrackMap.test.jsx
  code/client/src/components/features/HikeDetails/index.js
  code/client/src/components/features/HutCard/HutCard.test.jsx
  code/client/src/components/features/HutDetails/TrackMap.test.jsx
  code/client/src/components/features/HutsFilters/Filters/Specs.test.jsx
  code/client/src/pages/ActivateAccount/ActivateAccount.jsx
  code/client/src/pages/ActivateAccount/ActivateAccount.test.jsx
  code/client/src/pages/BrowseHikes/Hike.jsx
  code/client/src/pages/SearchHuts/SearchHuts.test.jsx
  code/client/src/pages/UpdateHikeEndpoints/UpdateHikeEndpoints.jsx
  code/client/src/pages/UpdateHikeEndpoints/UpdateHikeEndpoints.test.jsx
  code/client/src/pages/UpdateHikeEndpoints/index.js
  code/client/src/pages/index.js
  code/client/src/scss/_map.scss
  code/client/src/services/hikes.js
  code/server/controllers/HikeManager.js
  code/server/gpx/gpxTestTrack.gpx
  code/server/middlewares/auth.js
  code/server/package-lock.json
  code/server/package.json
  doc/mocks/Update Hikes/SelectEndpoints.jpg
Labels: enhancement, tests

#52 Frontend review, Update reference points, Undefined ascent issue and other improvements
  README.md
  code/client/package.json
  code/client/src/API.js
  code/client/src/App.jsx
  code/client/src/components/features/HikeCard/HikeCard.jsx
  code/client/src/components/features/HikeCard/HikeCard.test.jsx
  code/client/src/components/features/HikeDetails/Details.jsx
  code/client/src/components/features/HikeDetails/Details.test.jsx
  code/client/src/components/features/HutCard/HutCard.jsx
  code/client/src/components/features/HutCard/HutCard.test.jsx
  code/client/src/components/form/Select.jsx
  code/client/src/components/form/Select.test.jsx
  code/client/src/components/ui-core/Tooltip/Tooltip.jsx
  code/client/src/components/ui-core/Tooltip/index.js
  code/client/src/components/ui-core/index.js
  code/client/src/data/navigation.js
  code/client/src/layouts/Header.jsx
  code/client/src/layouts/Header.test.jsx
  code/client/src/layouts/MobileSidebar.jsx
  code/client/src/layouts/MobileSidebar.test.jsx
  code/client/src/pages/Authentication/ActivateAccount/ActivateAccount.jsx
  code/client/src/pages/Authentication/ActivateAccount/ActivateAccount.test.jsx
  code/client/src/pages/Authentication/ActivateAccount/index.js
  code/client/src/pages/Authentication/Login/Login.jsx
  code/client/src/pages/Authentication/Login/Login.test.jsx
  code/client/src/pages/Authentication/Login/index.js
  code/client/src/pages/Authentication/Signup/Signup.jsx
  code/client/src/pages/Authentication/Signup/Signup.test.jsx
  code/client/src/pages/Authentication/Signup/index.js
  code/client/src/pages/Authentication/index.js
  code/client/src/pages/BrowseHikes/BrowseHikes.jsx
  code/client/src/pages/HikeForm/gpxTestTrack.gpx
  code/client/src/pages/HikeForm/index.js
  code/client/src/pages/HikeList/HikeList.test.jsx
  code/client/src/pages/HikeList/index.js
  code/client/src/pages/Home/Home.jsx
  code/client/src/pages/Home/Home.test.jsx
  code/client/src/pages/HutForm/index.js
  code/client/src/pages/HutList/HutList.jsx
  code/client/src/pages/HutList/index.js
  code/client/src/pages/LocalGuide/Hikes/Add.jsx
  code/client/src/pages/LocalGuide/Hikes/Add.test.jsx
  code/client/src/pages/LocalGuide/Hikes/List.jsx
  code/client/src/pages/LocalGuide/Hikes/List.test.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateEndpoints.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateEndpoints.test.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateReferencePoints.jsx
  code/client/src/pages/LocalGuide/Hikes/index.js
  code/client/src/pages/LocalGuide/Huts/Add.jsx
  code/client/src/pages/LocalGuide/Huts/Add.test.jsx
  code/client/src/pages/LocalGuide/Huts/List.jsx
  code/client/src/pages/LocalGuide/Huts/List.test.jsx
  code/client/src/pages/LocalGuide/Huts/index.js
  code/client/src/pages/LocalGuide/ParkingLots/Add.jsx
  code/client/src/pages/LocalGuide/ParkingLots/index.js
  code/client/src/pages/LocalGuide/index.js
  code/client/src/pages/index.js
  code/client/src/scss/_bootstrap.scss
  code/client/src/services/hikes.js
Labels: documentation, enhancement, project management

#58 New Hut form fields
  code/client/src/components/form/Input.jsx
  code/client/src/lib/validations/HutSchema.js
  code/client/src/lib/validations/index.js
  code/client/src/pages/LocalGuide/Huts/Add.jsx
  code/client/src/pages/LocalGuide/Huts/Add.test.jsx
Labels: enhancement

#57 Added capacity and altitude for Describe parking
  code/client/src/lib/validations/ParkingLotSchema.js
  code/client/src/pages/LocalGuide/ParkingLots/Add.jsx
  code/client/src/services/parkingLots.js
  code/server/DB.test.db
  code/server/controllers/HikeManager.js
  code/server/controllers/PointManager.js
  code/server/controllers/UserManager.js
  code/server/dao/PersistentManager.js
  code/server/index.js
  code/server/middlewares/mail.js
  code/server/routes/parkingLot.router.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/__tests__/Hut.test.js
  code/server/test/hike.js
  code/server/test/integration-utils.js
  code/server/test/unit-utils.js
Labels: enhancement

#59 Distance formula for Linkable huts API fixed
  code/server/controllers/HikeManager.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/unit-utils.js
Labels: enhancement

#60 Frontend UI, connected APIs and tests for Link Huts and Geolocalization issue
  code/client/public/index.html
  code/client/src/App.jsx
  code/client/src/components/features/HikeDetails/Details.jsx
  code/client/src/components/features/HikeDetails/TrackMap.jsx
  code/client/src/components/features/HikesFilters/Filters/Position.jsx
  code/client/src/components/features/HikesFilters/Filters/Position.test.jsx
  code/client/src/components/features/HutsFilters/Filters/Position.jsx
  code/client/src/components/features/HutsFilters/Filters/Position.test.jsx
  code/client/src/components/ui-core/Tooltip/Tooltip.test.jsx
  code/client/src/layouts/MobileSidebar.jsx
  code/client/src/lib/helpers/filters.js
  code/client/src/lib/validations/HutSchema.js
  code/client/src/pages/BrowseHikes/Hike.jsx
  code/client/src/pages/BrowseHikes/Hike.test.jsx
  code/client/src/pages/LocalGuide/Hikes/List.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateEndpoints.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateEndpoints.test.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateLinkedHuts.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateLinkedHuts.test.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateReferencePoints.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateReferencePoints.test.jsx
  code/client/src/pages/LocalGuide/Hikes/index.js
  code/client/src/pages/LocalGuide/ParkingLots/Add.test.jsx
  code/client/src/pages/UpdateHikeEndpoints/index.js
  code/client/src/services/hikes.js
  code/client/src/services/huts.js
Labels: enhancement, tests

#48 Fixed search huts frontend
  code/client/src/components/features/HikesFilters/Filters/Position.jsx
  code/client/src/components/features/HutCard/HutCard.test.jsx
  code/client/src/components/features/HutsFilters/Filters/GeoArea.test.jsx
  code/client/src/components/features/HutsFilters/Filters/Specs.test.jsx
  code/client/src/components/features/HutsFilters/FiltersForm.jsx
  code/client/src/components/features/HutsFilters/HutsFilters.jsx
  code/client/src/components/features/Map/RadiusOnPoint.test.jsx
  code/client/src/contexts/index.js
  code/client/src/lib/helpers/filters.js
  code/client/src/pages/LocalGuide/Huts/Add.jsx
  code/client/src/pages/SearchHuts/SearchHuts.test.jsx
Labels: enhancement, tests

#53 Sonarcloud coverage report
  .github/workflows/sonarcloud.yml
  .github/workflows/tests.yml
  README.md
  code/client/.babelrc
  code/client/cypress.config.js
  code/client/cypress/e2e/hike-form.spec.cy.js
  code/client/cypress/e2e/signup.spec.cy.js
  code/client/cypress/e2e/update-hike-endpoints.spec.cy.js
  code/client/cypress/fixtures/huts/hut1.json
  code/client/cypress/fixtures/parkingLots/parkingLot1.json
  code/client/cypress/support/e2e.js
  code/client/package-lock.json
  code/client/package.json
  code/server/DB.test.db
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/auth.router.js
  sonar-project.properties
Labels: enhancement, project management

#66 Fixed bug on linking start/arrival
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeManager.js
  code/server/dbschema.sql
Labels: bug

#65 update DB structure in documentation
  README.md
  code/server/controllers/HikeManager.js
Labels: documentation

#67 Updated API documentation
  README.md
  code/server/DB.db
  code/server/DB.test.db
  code/server/dbschema.sql
Labels: documentation, enhancement
