Repository SoftwareEngineeringII-Team09/se-2022-09-HikeTracker, pull requests merged in 2022-11, with the labels that each got.

#1 Layout and Homepage
  code/client/jsconfig.json
  code/client/src/App.jsx
  code/client/src/App.test.js
  code/client/src/App.test.jsx
  code/client/src/assets/home_bg.jpg
  code/client/src/assets/logo/logo-black.png
  code/client/src/assets/logo/logo-color.png
  code/client/src/assets/logo/logo-no-background.png
  code/client/src/assets/logo/logo-white.png
  code/client/src/components/ui-core/NavLink/NavLink.jsx
  code/client/src/components/ui-core/NavLink/NavLink.test.jsx
  code/client/src/components/ui-core/NavLink/index.js
  code/client/src/components/ui-core/index.js
  code/client/src/data/index.js
  code/client/src/data/navigation.js
  code/client/src/layouts/Visitors/Header.jsx
  code/client/src/layouts/Visitors/Layout.jsx
  code/client/src/layouts/Visitors/MobileSidebar.jsx
  code/client/src/layouts/Visitors/index.js
  code/client/src/layouts/index.js
  code/client/src/pages/Error.jsx
  code/client/src/pages/Home.jsx
  code/client/src/pages/Home/Home.jsx
  code/client/src/pages/Home/Home.test.jsx
  code/client/src/pages/Home/index.js
  code/client/src/scss/_app.scss
  code/client/src/scss/_bootstrap.scss
  code/client/src/scss/_colors.scss
Labels: enhancement

#2 Homepage and visitors Layout tests
  code/client/craco.config.js
  code/client/jsconfig.json
  code/client/package-lock.json
  code/client/package.json
  code/client/src/App.jsx
  code/client/src/App.test.jsx
  code/client/src/components/ui-core/NavLink/NavLink.jsx
  code/client/src/components/ui-core/NavLink/NavLink.test.jsx
  code/client/src/data/navigation.js
  code/client/src/layouts/Visitors/Header.jsx
  code/client/src/layouts/Visitors/Header.test.jsx
  code/client/src/layouts/Visitors/Layout.test.jsx
  code/client/src/layouts/Visitors/MobileSidebar.jsx
  code/client/src/layouts/Visitors/MobileSidebar.test.jsx
  code/client/src/pages/Error.test.jsx
  code/client/src/pages/Home/Home.jsx
  code/client/src/pages/Home/Home.test.jsx
  code/client/src/setupTests.js
Labels: tests

#5 Define APIs to retrieve all the hikes and more info for a specific hike
  code/server/controllers/HikeManager.js
  code/server/controllers/HutManager.js
  code/server/controllers/ParkingLotManager.js
  code/server/controllers/PointManager.js
  code/server/controllers/UserManager.js
  code/server/dao/model/Hike.js
  code/server/dao/model/Hut.js
  code/server/dao/model/ParkingLot.js
  code/server/dao/model/Point.js
  code/server/dao/model/User.js
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/hike.router.js
Labels: enhancement

#4 Define frontend for Browse Hikes and for Hike Details
  code/client/package-lock.json
  code/client/package.json
  code/client/public/index.html
  code/client/src/App.jsx
  code/client/src/components/features/HikeCard/HikeCard.jsx
  code/client/src/components/features/HikeCard/HikeCard.test.jsx
  code/client/src/components/features/HikeCard/index.js
  code/client/src/components/features/HikeDetails/Details.jsx
  code/client/src/components/features/HikeDetails/Details.test.jsx
  code/client/src/components/features/HikeDetails/TrackMap.jsx
  code/client/src/components/features/HikeDetails/TrackMap.test.jsx
  code/client/src/components/features/HikeDetails/index.js
  code/client/src/components/features/HikesFilters/FilterRadioButton.jsx
  code/client/src/components/features/HikesFilters/FilterRadioButton.test.jsx
  code/client/src/components/features/HikesFilters/GeoAreaFilter.jsx
  code/client/src/components/features/HikesFilters/GeoAreaFilter.test.jsx
  code/client/src/components/features/HikesFilters/HikesFilters.jsx
  code/client/src/components/features/HikesFilters/HikesFilters.test.jsx
  code/client/src/components/features/HikesFilters/index.js
  code/client/src/components/features/index.js
  code/client/src/data/cities.json
  code/client/src/data/filters.js
  code/client/src/data/index.js
  code/client/src/data/provinces.json
  code/client/src/layouts/Visitors/Header.test.jsx
  code/client/src/layouts/Visitors/Layout.jsx
  code/client/src/lib/helpers/filters.js
  code/client/src/lib/helpers/index.js
  code/client/src/lib/helpers/location.js
  code/client/src/pages/BrowseHikes/BrowseHikes.jsx
  code/client/src/pages/BrowseHikes/BrowseHikes.test.jsx
  code/client/src/pages/BrowseHikes/Hike.jsx
  code/client/src/pages/BrowseHikes/index.js
  code/client/src/pages/Home/Home.jsx
  code/client/src/pages/index.js
  code/client/src/scss/_bootstrap.scss
  code/client/src/scss/_map.scss
  code/client/src/scss/index.scss
Labels: enhancement, tests

#9 Login/Register APIs and Connect Hikes API to frontend
  code/client/src/API.js
  code/client/src/services/api.js
  code/client/src/services/config.js
  code/client/src/services/hikes.js
  code/client/src/services/huts.js
  code/client/src/services/index.js
  code/client/src/services/users.js
  code/server/controllers/UserManager.js
  code/server/dao/model/Mail.js
  code/server/dao/model/User.js
  code/server/db.db
  code/server/index.js
  code/server/middlewares/auth.js
  code/server/middlewares/mail.js
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/auth.router.js
  code/server/routes/hike.router.js
  code/server/validations/authValidation.js
Labels: bug, enhancement

#7 Registration, Login, Account Activation UI
  README.md
  code/client/craco.config.js
  code/client/package-lock.json
  code/client/package.json
  code/client/src/App.jsx
  code/client/src/components/ui-core/NavLink/NavLink.test.jsx
  code/client/src/contexts/authContext.jsx
  code/client/src/index.js
  code/client/src/layouts/Visitors/Header.test.jsx
  code/client/src/layouts/Visitors/MobileSidebar.test.jsx
  code/client/src/pages/ActivateAccount/ActivateAccount.jsx
  code/client/src/pages/ActivateAccount/ActivateAccount.test.jsx
  code/client/src/pages/ActivateAccount/index.js
  code/client/src/pages/Home/Home.jsx
  code/client/src/pages/Home/Home.test.jsx
  code/client/src/pages/Login/Login.jsx
  code/client/src/pages/Login/Login.test.jsx
  code/client/src/pages/Login/index.js
  code/client/src/pages/Signup/Signup.jsx
  code/client/src/pages/Signup/Signup.test.jsx
  code/client/src/pages/Signup/index.js
  code/client/src/pages/index.js
  code/client/src/scss/_app.scss
  code/client/src/services/users.js
  doc/mocks/Account/Login.png
  doc/mocks/Account/Register_additional_info.png
  doc/mocks/Account/Register_default.png
  package-lock.json
Labels: enhancement, tests

#8 APIs to add a new hike and to add a new hut and DB
  README.md
  code/client/package-lock.json
  code/server/controllers/HikeManager.js
  code/server/controllers/HutManager.js
  code/server/dao/model/Hike.js
  code/server/dao/model/Hike_Ref.js
  code/server/dao/model/Hut.js
  code/server/dao/model/Hut_Hike.js
  code/server/dao/model/Opening_hours.js
  code/server/dao/model/ParkingLot.js
  code/server/dao/model/Point.js
  code/server/dao/model/User.js
  code/server/db.db
  code/server/gpx/rocciamelone.gpx
  code/server/index.js
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/hike.router.js
  code/server/routes/hut.router.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/__tests__/Hut.test.js
  code/server/test/hike.js
Labels: enhancement, tests

#11 adding integration and unit tests for retrieving hikes
  code/package-lock.json
  code/server/controllers/HikeManager.js
  code/server/dao/PersistentManager.js
  code/server/db.db
  code/server/gpx/bivacco_berardo.gpx
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/hike.router.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/__tests__/Hut.test.js
  code/server/test/__tests__/ParkingLot.test.js
  code/server/test/hike.js
  code/server/test/utils.js
Labels: tests

#18 GitHub checks and docker auto-deploy configuration
  .DS_Store
  .github/workflows/docker-build.yml
  .github/workflows/docker-release.yml
  .github/workflows/tests.yml
  README.md
  code/docker-compose.prod.yml
Labels: project management

#19 Integration tests for login/registration/mail verification, E2E Tests setup
  README.md
  code/client/cypress.config.js
  code/client/cypress/e2e/login.spec.cy.js
  code/client/cypress/fixtures/example.json
  code/client/cypress/support/commands.js
  code/client/cypress/support/e2e.js
  code/client/cypress/support/index.js
  code/client/package-lock.json
  code/client/package.json
  code/client/src/contexts/authContext.jsx
  code/client/src/pages/ActivateAccount/ActivateAccount.jsx
  code/client/src/pages/ActivateAccount/ActivateAccount.test.jsx
  code/client/src/pages/Login/Login.jsx
  code/client/src/pages/Login/Login.test.jsx
  code/client/src/pages/Signup/Signup.jsx
  code/client/src/pages/Signup/Signup.test.jsx
  code/client/src/scss/_app.scss
  code/client/src/services/api.js
  code/client/src/services/users.js
Labels: tests

#20 Added integration tests for hike/hut/parkingLot and unit tests for hike
  code/server/DB.db
  code/server/controllers/HikeHutManager.js
  code/server/controllers/HikeManager.js
  code/server/controllers/HikeParkingLotManager.js
  code/server/controllers/HikeRefPointManager.js
  code/server/controllers/HutDailyScheduleManager.js
  code/server/controllers/HutManager.js
  code/server/controllers/ParkingLotManager.js
  code/server/controllers/PointManager.js
  code/server/dao/PersistentManager.js
  code/server/dao/model/ParkingLot.js
  code/server/dao/model/Point.js
  code/server/dbschema.sql
  code/server/index.js
  code/server/routes/hike.router.js
  code/server/routes/hut.router.js
  code/server/routes/parkingLot.router.js
  code/server/routes/parkinglot.router.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/__tests__/Hut.test.js
  code/server/test/__tests__/ParkingLot.test.js
  code/server/test/__tests__/User.test.js
  code/server/test/hike.js
  code/server/test/hut.js
  code/server/test/integration-utils.js
  code/server/test/parkingLot.js
  code/server/test/parkinglot.js
  code/server/test/unit-utils.js
  code/server/test/user.js
  code/server/test/utils.js
Labels: tests

#21 Added API for describing a parkingLot
  code/server/controllers/HikeHutManager.js
  code/server/controllers/HikeManager.js
  code/server/controllers/HikeParkingLotManager.js
  code/server/controllers/HikeRefPointManager.js
  code/server/controllers/HutDailyScheduleManager.js
  code/server/controllers/HutManager.js
  code/server/controllers/ParkingLotManager.js
  code/server/test/__tests__/HikeRefPoint.test.js
  code/server/test/__tests__/ParkingLot.test.js
  code/server/test/__tests__/Point.test.js
  code/server/test/unit-utils.js
Labels: enhancement, tests

#23 adding testing of hut and defineHike
  README.md
  code/server/DB.db
  code/server/controllers/HikeManager.js
  code/server/controllers/HikeRefPointManager.js
  code/server/controllers/HutDailyScheduleManager.js
  code/server/controllers/HutManager.js
  code/server/dbschema.sql
  code/server/routes/hike.router.js
  code/server/routes/hut.router.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/__tests__/Hut.test.js
  code/server/test/unit-utils.js
Labels: tests

#24 Sonarcloud Github action configuration
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: project management

#28 Added linking of huts/parkings as start/end point
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeHutManager.js
  code/server/controllers/HikeManager.js
  code/server/controllers/HikeParkingLotManager.js
  code/server/controllers/HikeRefPointManager.js
  code/server/controllers/HutDailyScheduleManager.js
  code/server/controllers/HutManager.js
  code/server/controllers/ParkingLotManager.js
  code/server/controllers/PointManager.js
  code/server/controllers/UserManager.js
  code/server/dao/PersistentManager.js
  code/server/dao/model/Mail.js
  code/server/dao/model/User.js
  code/server/dbschema.sql
  code/server/dbschemaTest.sql
  code/server/index.js
  code/server/middlewares/auth.js
  code/server/middlewares/mail.js
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/auth.router.js
  code/server/routes/hike.router.js
  code/server/routes/hut.router.js
  code/server/routes/parkingLot.router.js
  code/server/routes/test.router.js
  code/server/setupDB.js
  code/server/validations/authValidation.js
Labels: enhancement

#22 Describe hikes and huts with unit tests
  code/client/src/App.jsx
  code/client/src/data/navigation.js
  code/client/src/pages/HikeForm/HikeForm.jsx
  code/client/src/pages/HikeForm/HikeForm.test.jsx
  code/client/src/pages/HikeForm/index.js
  code/client/src/pages/HikeList/HikeList.jsx
  code/client/src/pages/HikeList/HikeList.test.jsx
  code/client/src/pages/HikeList/index.js
  code/client/src/pages/HutForm/HutForm.jsx
  code/client/src/pages/HutForm/HutForm.test.jsx
  code/client/src/pages/HutForm/index.js
  code/client/src/pages/HutList/HutList.jsx
  code/client/src/pages/HutList/HutList.test.jsx
  code/client/src/pages/HutList/index.js
  code/client/src/pages/index.js
  doc/mocks/Search Huts/search huts.pdf
Labels: enhancement, tests

#34 Authentication, Routes protection and Describe parking lot
  code/client/package-lock.json
  code/client/package.json
  code/client/public/index.html
  code/client/src/App.jsx
  code/client/src/components/features/HikeCard/HikeCard.jsx
  code/client/src/components/features/HikeCard/HikeCard.test.jsx
  code/client/src/components/features/HikeDetails/TrackMap.jsx
  code/client/src/components/features/HikeDetails/TrackMap.test.jsx
  code/client/src/components/features/HikesFilters/Filters/Position.jsx
  code/client/src/components/features/Map/MarkerOnPoint.jsx
  code/client/src/components/features/Map/index.js
  code/client/src/components/features/ProtectedRoute/ProtectedRoute.jsx
  code/client/src/components/form/Select.jsx
  code/client/src/contexts/authContext.jsx
  code/client/src/data/navigation.js
  code/client/src/layouts/Header.jsx
  code/client/src/layouts/Header.test.jsx
  code/client/src/layouts/Layout.jsx
  code/client/src/layouts/Layout.test.jsx
  code/client/src/layouts/MobileSidebar.jsx
  code/client/src/layouts/MobileSidebar.test.jsx
  code/client/src/layouts/Visitors/MobileSidebar.jsx
  code/client/src/layouts/Visitors/MobileSidebar.test.jsx
  code/client/src/layouts/Visitors/index.js
  code/client/src/layouts/index.js
  code/client/src/lib/helpers/filters.js
  code/client/src/lib/validations/ParkingLotSchema.js
  code/client/src/lib/validations/SignupSchema.js
  code/client/src/lib/validations/index.js
  code/client/src/pages/ActivateAccount/ActivateAccount.jsx
  code/client/src/pages/ActivateAccount/ActivateAccount.test.jsx
  code/client/src/pages/BrowseHikes/BrowseHikes.jsx
  code/client/src/pages/BrowseHikes/Hike.jsx
  code/client/src/pages/HikeForm/HikeForm.jsx
  code/client/src/pages/HutForm/HutForm.jsx
  code/client/src/pages/LocalGuide/AddParkingLot.jsx
  code/client/src/pages/LocalGuide/index.js
  code/client/src/pages/Login/Login.jsx
  code/client/src/pages/Login/Login.test.jsx
  code/client/src/pages/Signup/Signup.jsx
  code/client/src/pages/Signup/Signup.test.jsx
  code/client/src/pages/index.js
  code/client/src/services/api.js
  code/client/src/services/hikes.js
  code/client/src/services/parkingLots.js
  code/client/src/services/users.js
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/UserManager.js
  code/server/index.js
  code/server/routes/auth.router.js
Labels: bug, enhancement, tests

#35 Added tests for linking of start/end points and fixed integration tests
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeManager.js
  code/server/controllers/HikeRefPointManager.js
  code/server/controllers/PointManager.js
  code/server/controllers/UserManager.js
  code/server/dao/model/HikeParkingLot.js
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/hike.router.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/__tests__/HikeRefPoint.test.js
  code/server/test/__tests__/Hut.test.js
  code/server/test/__tests__/ParkingLot.test.js
  code/server/test/__tests__/Point.test.js
  code/server/test/__tests__/User.test.js
  code/server/test/hike.js
  code/server/test/hut.js
  code/server/test/integration-utils.js
  code/server/test/parkingLot.js
  code/server/test/unit-utils.js
Labels: enhancement, tests

#36 Added documentation about /login /signup and /activate frontend routes
  README.md
Labels: documentation

#37 Updated server routes documentation
  README.md
  code/server/controllers/HikeManager.js
  code/server/routes/auth.router.js
Labels: documentation

#40 Login and signup E2E tests
  code/client/cypress/e2e/login.spec.cy.js
  code/client/cypress/e2e/signup.spec.cy.js
  code/client/src/services/config.js
Labels: tests

#38 Fixing bug on describe parking
  code/server/controllers/ParkingLotManager.js
  code/server/routes/parkingLot.router.js
  code/server/test/__tests__/ParkingLot.test.js
  code/server/test/parkingLot.js
Labels: enhancement

#31 Added region in hut and hike form
  code/client/cypress/e2e/hike-form.spec.cy.js
  code/client/src/App.jsx
  code/client/src/components/features/HutCard/HutCard.jsx
  code/client/src/components/features/HutCard/HutCard.test.jsx
  code/client/src/components/features/HutCard/index.js
  code/client/src/components/features/HutDetails/Details.jsx
  code/client/src/components/features/HutDetails/Details.test.jsx
  code/client/src/components/features/HutDetails/TrackMap.jsx
  code/client/src/components/features/HutDetails/TrackMap.test.jsx
  code/client/src/components/features/HutDetails/index.js
  code/client/src/components/features/HutsFilters/Filters/GeoArea.jsx
  code/client/src/components/features/HutsFilters/Filters/GeoArea.test.jsx
  code/client/src/components/features/HutsFilters/Filters/Location.jsx
  code/client/src/components/features/HutsFilters/Filters/Location.test.jsx
  code/client/src/components/features/HutsFilters/Filters/Position.jsx
  code/client/src/components/features/HutsFilters/Filters/Position.test.jsx
  code/client/src/components/features/HutsFilters/Filters/Specs.jsx
  code/client/src/components/features/HutsFilters/Filters/Specs.test.jsx
  code/client/src/components/features/HutsFilters/Filters/index.js
  code/client/src/components/features/HutsFilters/FiltersForm.jsx
  code/client/src/components/features/HutsFilters/HutsFilters.jsx
  code/client/src/components/features/HutsFilters/HutsFilters.test.jsx
  code/client/src/components/features/HutsFilters/index.js
  code/client/src/components/features/index.js
  code/client/src/contexts/FiltersContextHuts.jsx
  code/client/src/data/test/gpxTestTrack.gpx
  code/client/src/lib/helpers/filters.js
  code/client/src/lib/helpers/location.js
  code/client/src/pages/HikeForm/HikeForm.jsx
  code/client/src/pages/HikeForm/HikeForm.test.jsx
  code/client/src/pages/HutForm/HutForm.jsx
  code/client/src/pages/SearchHuts/Hut.jsx
  code/client/src/pages/SearchHuts/SearchHuts.jsx
  code/client/src/pages/SearchHuts/SearchHuts.test.jsx
  code/client/src/pages/SearchHuts/index.js
  code/client/src/pages/index.js
  code/client/src/services/api.js
  code/client/src/services/huts.js
  code/server/DB.test.db
  code/server/controllers/HutManager.js
  code/server/gpx/bivacco_berardo.gpx
  code/server/index.js
  code/server/middlewares/auth.js
  code/server/routes/auth.router.js
  code/server/routes/hut.router.js
  code/server/test/hut.js
  code/server/test/integration-utils.js
Labels: enhancement

#41 Adding reference points UI and Map in HutForm
  code/client/src/App.jsx
  code/client/src/components/features/HikeDetails/TrackMap.jsx
  code/client/src/data/navigation.js
  code/client/src/lib/validations/ReferencePointSchema.js
  code/client/src/lib/validations/index.js
  code/client/src/pages/HikeForm/HikeForm.test.jsx
  code/client/src/pages/HikeForm/gpxTestTrack.gpx
  code/client/src/pages/HutForm/HutForm.jsx
  code/client/src/pages/HutForm/HutForm.test.jsx
  code/client/src/pages/LocalGuide/AddParkingLot.jsx
  code/client/src/pages/LocalGuide/ReferencePoints.jsx
  code/client/src/pages/LocalGuide/index.js
  code/client/src/services/hikes.js
  code/server/dbschema.sql
Labels: enhancement

#42 Add initialvalue in DB & Updated Post reference Point
  README.md
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeRefPointManager.js
  code/server/dbschema.sql
  code/server/gpx/Alagna Valsesia - Sorgenti del Sesia.gpx
  code/server/gpx/Anello Val Servin .gpx
  code/server/gpx/Borgata Rua-Cima di Crosa.gpx
  code/server/gpx/Cima del Bosco.gpx
  code/server/gpx/Colombardo da Pratobotrile.gpx
  code/server/gpx/Hike_Zicher.gpx
  code/server/gpx/Laghetti Verdi e Lago Paschiet.gpx
  code/server/gpx/Laghi Paione.gpx
  code/server/gpx/Lago Panelatte.gpx
  code/server/gpx/Lago di Afframont.gpx
  code/server/gpx/Monte Riba del Gias da Becetto.gpx
  code/server/gpx/Poggio Tre Croci Ciaspole.gpx
  code/server/gpx/Punta Nera e Colle della Rho.gpx
  code/server/gpx/alpe dattia da ala.gpx
  code/server/gpx/anello Rocca sella e monte sapei .gpx
  code/server/gpx/monte musine.gpx
  code/server/gpx/pian dell azaria.gpx
  code/server/gpx/pietraborga da piossasco.gpx
  code/server/gpx/rifugio paolo daviso.gpx
  code/server/gpx/sacra di San Michele .gpx
  code/server/package-lock.json
  code/server/routes/hike.router.js
  code/server/routes/hut.router.js
  code/server/test/hike.js
  code/server/test/hut.js
  code/server/test/integration-utils.js
Labels: enhancement, project management
