Repository SoftwareEngineeringII-Team09/se-2022-09-HikeTracker, pull requests merged in 2023-01, with the labels that each got.

#71 Review of Signup workflow + fixes
  README.md
  code/client/.gitignore
  code/client/src/components/features/HikeDetails/TrackMap.jsx
  code/client/src/components/form/LoadingButton.jsx
  code/client/src/components/form/LoadingButton.test.jsx
  code/client/src/components/form/index.js
  code/client/src/contexts/authContext.jsx
  code/client/src/lib/validations/HutSchema.js
  code/client/src/pages/Authentication/ActivateAccount/ActivateAccount.jsx
  code/client/src/pages/Authentication/Login/Login.jsx
  code/client/src/pages/Authentication/Signup/Signup.jsx
  code/client/src/pages/LocalGuide/Hikes/Add.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateEndpoints.jsx
  code/client/src/pages/LocalGuide/Huts/Add.jsx
  code/server/index.js
  code/server/routes/hike.router.js
Labels: enhancement, tests

#79 Hike's data update after linking of start/end point + backend coverage update
  README.md
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeManager.js
  code/server/controllers/SelectedHikeManager.js
  code/server/index.js
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/auth.router.js
  code/server/routes/hike.router.js
  code/server/routes/user.router.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/auth.js
  code/server/test/hike.js
  code/server/test/hut.js
  code/server/test/integration-utils.js
Labels: bug, enhancement, tests

#77 getSelectedHike, startHike and cover images APIs
  code/client/package-lock.json
  code/client/package.json
  code/server/DB.db
  code/server/DB.test.db
  code/server/controllers/HikeManager.js
  code/server/controllers/HutManager.js
  code/server/controllers/SelectedHikeManager.js
  code/server/dao/model/Hike.js
  code/server/dao/model/Hut.js
  code/server/dao/model/SelectedHike.js
  code/server/dbschema.sql
  code/server/dbschemaTest.sql
  code/server/gpx/test.gpx
  code/server/hikeImage/hike1.jpg
  code/server/hutImage/hut1.jpg
  code/server/hutImage/hut2.jpeg
  code/server/package-lock.json
  code/server/package.json
  code/server/routes/hike.router.js
  code/server/routes/hut.router.js
  code/server/routes/selectedHike.router.js
  code/server/setupDB.js
  code/server/test/__tests__/Hike.test.js
  code/server/test/__tests__/Hut.test.js
  code/server/test/__tests__/SelectedHike.test.js
  code/server/test/hike.js
  code/server/test/hut.js
  code/server/test/integration-utils.js
  code/server/test/selectedHike.js
  code/server/test/unit-utils.js
  package-lock.json
  package.json
Labels: enhancement, tests

#81 Completed hikes frontend
  code/client/cypress/e2e/completed-hikes/completed-hikes.spec.cy.js
  code/client/cypress/support/commands.js
  code/client/src/App.jsx
  code/client/src/data/navigation.js
  code/client/src/pages/CompletedHikes/CompletedHikes.jsx
  code/client/src/pages/CompletedHikes/CompletedHikes.test.jsx
  code/client/src/pages/CompletedHikes/index.js
  code/client/src/pages/index.js
  code/client/src/services/hikes.js
  code/server/routes/test.router.js
Labels: enhancement, tests

#80 Terminate hikes
  code/client/cypress/e2e/browse-hikes/details.spec.cy.js
  code/client/cypress/e2e/completed-hikes/completed-hikes.spec.cy.js
  code/client/cypress/support/commands.js
  code/client/package-lock.json
  code/client/package.json
  code/client/src/components/features/HikeDetails/Details.jsx
  code/client/src/components/features/HikeDetails/Details.terminate.test.jsx
  code/client/src/components/features/HikeDetails/Details.test.jsx
  code/client/src/contexts/authContext.jsx
  code/client/src/data/test/hut.jpg
  code/client/src/lib/validations/HikeSchema.js
  code/client/src/lib/validations/HutSchema.js
  code/client/src/pages/Authentication/ActivateAccount/ActivateAccount.jsx
  code/client/src/pages/LocalGuide/Hikes/Add.jsx
  code/client/src/pages/LocalGuide/Hikes/Add.test.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateEndpoints.jsx
  code/client/src/pages/LocalGuide/Huts/Add.test.jsx
  code/client/src/services/api.js
  code/client/src/services/selectedHikes.js
  code/server/controllers/SelectedHikeManager.js
  code/server/routes/test.router.js
  code/server/test/__tests__/SelectedHike.test.js
  code/server/test/unit-utils.js
Labels: enhancement, tests

#73 Unit and E2E tests for search hut fixed
  code/client/cypress/e2e/local-guide/create-new-hike.spec.cy.js
  code/client/cypress/e2e/local-guide/hut-form.spec.cy.js
  code/client/cypress/e2e/local-guide/list-hut.spec.cy.js
  code/client/cypress/e2e/search-huts/hut-details.spec.cy.js
  code/client/cypress/e2e/search-huts/search-hut.spec.cy.js
  code/client/cypress/fixtures/images/test.jpeg
  code/client/src/components/features/HutCard/HutCard.test.jsx
  code/client/src/components/features/HutDetails/TrackMap.test.jsx
  code/client/src/lib/helpers/filters.js
  code/server/DB.test.db
  code/server/hikeImage/test.jpeg
  code/server/hutImage/test.jpeg
Labels: tests

#85 ReadMeUpdate
  README.md
  code/server/controllers/SelectedHikeManager.js
Labels: documentation

#83 Integration and E2E tests for start hike and cover images UI fixed
  code/client/cypress/e2e/browse-hikes/details.spec.cy.js
  code/client/cypress/e2e/completed-hikes/completed-hikes.spec.cy.js
  code/client/cypress/e2e/hiker/start-hike.spec.cy.js
  code/client/cypress/fixtures/hiker/auth-current-response.json
  code/client/cypress/fixtures/hiker/start-hike-response.json
  code/client/cypress/fixtures/hiker/started-hike-response.json
  code/client/cypress/integrations/hiker/start-hike.integration.test.js
  code/client/src/components/features/HikeCard/HikeCard.jsx
  code/client/src/components/features/HikeDetails/Details.jsx
  code/client/src/components/features/HikesFilters/Filters/GeoArea.jsx
  code/client/src/components/features/HikesFilters/Filters/Position.jsx
  code/client/src/components/features/HikesFilters/FiltersForm.jsx
  code/client/src/components/features/HikesFilters/HikesFilters.jsx
  code/client/src/components/features/HutCard/HutCard.jsx
  code/client/src/components/features/HutDetails/Details.jsx
  code/client/src/components/features/HutsFilters/Filters/GeoArea.jsx
  code/client/src/components/features/HutsFilters/FiltersForm.jsx
  code/client/src/layouts/Header.jsx
  code/client/src/layouts/MobileSidebar.jsx
  code/client/src/pages/Authentication/Login/Login.jsx
  code/client/src/pages/Authentication/Signup/Signup.jsx
  code/client/src/pages/Authentication/Signup/Signup.test.jsx
  code/client/src/pages/BrowseHikes/BrowseHikes.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateLinkedHuts.jsx
  code/client/src/pages/LocalGuide/Hikes/UpdateReferencePoints.jsx
  code/client/src/pages/LocalGuide/Huts/Add.jsx
  code/client/src/pages/LocalGuide/ParkingLots/Add.jsx
  code/server/hikeImage/cover.jpeg
  sonar-project.properties
Labels: enhancement, tests
